### ISSUE TITLE
cloud9上のよくわからないバグ？

### ISSUE THREAD

**Issue by Momiji-otete** [macarons-a/nagano_cake#16]
kaminariを使えるようにするためにdevelopからブランチを分けたところ、なぜかついさっきまで記述があったはずのadmin/itemsコントローラーの記述が全部消えてました。ローカルのdevelopとkaminariを使えるように分けたブランチの両方から消えてました。対処したやり方としては、git add、commit 前に気づいたので、git statusで差分を確認して、git restore ファイル名で修復した後、そのままgit add、commit をしたら解決できた感じです。なんかやらかしたかと思いました、勘弁してくれ～～～

**Comment by chip-k** [comment]
同じことが起きたら参考にします！
