### ISSUE TITLE
注文確定画面でリロードするとエラーが出る。

### ISSUE THREAD

**Issue by hitotmi** [macarons-a/nagano_cake#34]
なぜかshowアクションに飛ぶ。エラー出る！

**Comment by Momiji-otete** [comment]
解決しようとしましたがうまくいきませんでした。無理そうだったら今度メンター呼びましょう

**Comment by Momiji-otete** [comment]
解決する必要がないエラーでした！本番環境では出ないエラーなので実質解決！！
