### ISSUE TITLE
会員の退会に関して

### ISSUE THREAD

**Issue by Momiji-otete** [macarons-a/nagano_cake#35]
退会するときに本当に退会しますか？ダイアログを出してもいいかも？
退会した会員でログインしようとしたときに新規登録画面に遷移するときにも、退会済みなので的なフラッシュメッセージを表示してもいいかも？？草稼ぎです。

**Comment by chip-k** [comment]
フラッシュメッセージは追加しました。

**Comment by Momiji-otete** [comment]
ありがとうございます
